# GetPlatformLibraries - determine the platform-specific libraries to link statically and save them as out_var
function(GetPlatformLibraries msg_prefix lib_var)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        if(MINGW)
            message(STATUS "${msg_prefix}: MinGW detected, linking to libm and libpthread")
            set(${lib_var} "m pthread" PARENT_SCOPE)
        else()
            message(STATUS "${msg_prefix}: GCC detected, linking to libm and libpthread")
            set(${lib_var} "m pthread" PARENT_SCOPE)
        endif()
    elseif(MSVC)
        message(STATUS "${msg_prefix}: MSVC detected, no additional libraries to link")
        set(${lib_var} "" PARENT_SCOPE)
    else()
        message(NOTICE "${msg_prefix}: Non-standard compiler detected!")
		set(${lib_var} "" PARENT_SCOPE)
    endif()
endfunction()